name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Capacitor deps
        run: |
          npm install --save @capacitor/core@5 @capacitor/cli@5 @capacitor/android@5

      - name: Init Capacitor
        run: |
          npx cap init CrazyZombie com.crazy.zombie --web-dir=www || true

      - name: Add Android
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CrazyZombie-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
